#CROSSCOMPILE SECTION
CROSSCOMPILE_HOSTNAME 	:= pi
CROSSCOMPILE_SSH_HOST 	:= 192.168.1.70
CROSSCOMPILE_DIR 	:= /home/pi

#The Directories and extensions SECTION
SRC_MODULES_DIR	   := Src_Modules
BUILDDIRECTORY 	   := Objects
TARGETDIRECTORY	   := Release
RESDIRECTORY  	   := Resources
LIBDIRECTORY	   := Libraries
HEADERSDIRECTORY   := Headers

DLEXT	:= so
SLEXT	:= a
SRCEXT	:= c
OBJEXT	:= o
HEADEXT	:= h
SRCDIR	:= src

#Modules SECTION
MODULEA := Application
MODULEB := StaticLibTest
MODULEC	:= SharedLibTest
MODULED := DataStructures

DEPMODULES	:= $(MODULEC) $(MODULEB) 
MAINMODULE	:= $(MODULEA)

LIBSTOLINK    	:=  -l $(MODULEB)\
	-l $(MODULEC)

#Compiler and archiver SECTION
TARGET 		:= Application
VERSION		:= Debugx64
CC 		:= gcc
ARCH		:= ar rcs
LIBSEARCHDIR	:= $(LIBDIRECTORY)/$(VERSION)/
LIBSRSEARCHPATH	:= /usr/lib/
CFLAGS		:= -g -Wall
LDFLAGS		:= -L ../../$(LIBSEARCHDIR) $(LIBSTOLINK) \
	-Wl,-rpath,$(LIBSRSEARCHPATH)
MACROS		:= -D DEBUG\
		-D Path=/usr/

#RUNNING 

EXECINSTALLDIR	:= /usr/bin/
LIBINSTALLDIR	:= /usr/lib/
RESINSTALLDIR	:= /usr/