TOP_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

#PROJECT SECTION
TARGET 		:= CortexM3App
TESTTYPE	:= Release
INSTRUCTIONS	:= Stm32F1
LIBRARIESTYPE	:= Static
VERSION		:= $(TESTTYPE)$(INSTRUCTIONS)$(LIBRARIESTYPE)

#The Directories and extensions SECTION
SRC_MODULES_DIR	   := Src_Modules
BUILDDIRECTORY 	   := Objects
TARGETDIRECTORY	   := Release
LIBDIRECTORY	   := Libraries
HEADERSDIRECTORY   := Headers

DLEXT   := so
SLEXT	:= a
CCEXT	:= c
CPPEXT	:= cpp
OBJEXT	:= o
ELFEXT	:= elf
MAPEXT	:= map
HEXEXT	:= hex
BINEXT	:= bin
HEADEXT	:= h
SRCDIR	:= src

#Modules SECTION
MODULEA := CortexM3App

DEPMODULES      :=
MAINMODULE	:= $(MODULEA)

#MICROCONTROLLER SPECIFIC
BOARDDEF	:= -DSTM32F1
FP_FLAGS	:= -msoft-float
ARCH_FLAGS	:= -mthumb -mcpu=cortex-m3 $(FP_FLAGS) -mfix-cortex-m3-ldrd
LDSCRIPT 	:= $(TOP_DIR)/stm32f103c8t6.ld
STFLASH		:= $(shell which st-flash)

#COMPILER SECTION
PREFIX		:= arm-none-eabi
CC		:= $(PREFIX)-gcc
CXX	  	:= $(PREFIX)-g++ 
LD		:= $(PREFIX)-gcc 
AR		:= $(PREFIX)-ar
OBJCOPY 	:= $(PREFIX)-objcopy
SIZE		:= $(PREFIX)-size
OPT		:= -Os -g
MACROS		:= $(BOARDDEF)\
-DSTM32F103xB	

CFLAGS		+= $(OPT) -std=c99
CFLAGS		+= $(ARCH_FLAGS)
CFLAGS		+= -Wextra -Wshadow -Wimplicit-function-declaration
CFLAGS		+= -Wredundant-decls -Wmissing-prototypes -Wstrict-prototypes
CFLAGS		+= -fno-common -ffunction-sections -fdata-sections

CXXFLAGS	+= $(OPT) -std=c++11
CXXFLAGS	+= $(ARCH_FLAGS)
CXXFLAGS	+= -Wextra -Wshadow -Wredundant-decls -Weffc++
CXXFLAGS	+= -fno-exceptions -fno-rtti
CXXFLAGS	+= -fno-common -ffunction-sections -fdata-sections

CPPFLAGS	+= -MMD -MP
CPPFLAGS 	+= -Wall $(MACROS)

LIBSTOLINK    	:= -lopencm3_stm32f1
LIBSEARCHDIR	:= $(LIBDIRECTORY)/$(VERSION)/

LDFLAGS		+= --static -nostartfiles
LDFLAGS		+= -T$(LDSCRIPT)
LDFLAGS 	+= $(ARCH_FLAGS)
LDFLAGS 	+= -Wl,-Map=$(TOP_DIR)/$(TARGETDIRECTORY)/$(VERSION)/$(*).map
LDFLAGS		+= -Wl,--gc-sections

LDFLAGS		+= -specs=nosys.specs
LDFLAGS		+= -Wl,--start-group -lc -lgcc -lnosys -Wl,--end-group
LDFLAGS		+= -L ../../$(LIBSEARCHDIR) $(LIBSTOLINK)

