
#The Directories and extensions SECTION
SRC_MODULES_DIR	   := Src_Modules
BUILDDIRECTORY 	   := Objects
TARGETDIRECTORY	   := Release
LIBDIRECTORY	   := Libraries
HEADERSDIRECTORY   := Headers

DLEXT   := so
SLEXT	:= a
SRCEXT	:= c
OBJEXT	:= o
ELFEXT	:= elf
HEXEXT	:= hex
HEADEXT	:= h
SRCDIR	:= src

#Modules SECTION
MODULEA := MicroC_Application

DEPMODULES      :=
MAINMODULE	:= $(MODULEA)


#MICROCONTROLLER SPECIFIC
AVRDUDECONF := /home/paul/arduino-1.8.6/hardware/tools/avr/etc/avrdude.conf
AVRDUDEDIR  := /home/paul/arduino-1.8.6/hardware/tools/avr/bin/avrdude
OBJCOPY := /home/paul/arduino-1.8.6/hardware/tools/avr/bin/avr-objcopy

DEVICE := atmega328p
BAUDRATE := 115200
CLOCK := 20000000

PROGRAMMER := -c arduino -P /dev/ttyACM0 -b 19200
FUSES := -U lfuse:w:0xd7:m -U hfuse:w:0xd9:m -U efuse:w:0xfc:m 
AVRDUDE := $(AVRDUDEDIR) -C $(AVRDUDECONF) $(PROGRAMMER) -p $(DEVICE)


#Compiler SECTION
TARGET 		:= MicroC_Application
TESTTYPE	:= Release
INSTRUCTIONS	:= Avr
LIBRARIESTYPE	:= Static
VERSION		:= $(TESTTYPE)$(INSTRUCTIONS)$(LIBRARIESTYPE)
CC 		:= /home/paul/arduino-1.8.6/hardware/tools/avr/bin/avr-gcc-5.4.0 -mmcu=$(DEVICE) 
ARCH		:= /home/paul/arduino-1.8.6/hardware/tools/avr/bin/avr-ar
CFLAGS		:= -Wall -Os -std=gnu99
MACROS		:= -DF_CPU=$(CLOCK)\
	-DBAUD=$(BAUDRATE)\
	-DUSE_2X
#-g for Debug

LIBSTOLINK    	:= -lm
LIBSEARCHDIR	:= $(LIBDIRECTORY)/$(VERSION)/
LDFLAGS		:= -L ../../$(LIBSEARCHDIR) $(LIBSTOLINK)


