#CROSSCOMPILE SECTION
CROSSCOMPILE_HOSTNAME 	:= 
CROSSCOMPILE_SSH_HOST 	:= 
CROSSCOMPILE_DIR 	:= 

#The Directories and extensions SECTION
SRC_MODULES_DIR	   := Src_Modules
BUILDDIRECTORY 	   := Objects
TARGETDIRECTORY	   := Release
RESDIRECTORY  	   := Resources
LIBDIRECTORY	   := Libraries
HEADERSDIRECTORY   := Headers

DLEXT	:= so
SLEXT	:= a
SRCEXT	:= c
OBJEXT	:= o
HEADEXT	:= h
SRCDIR	:= src

#Modules SECTION
MODULEA := Application

DEPMODULES	:= 
MAINMODULE	:= $(MODULEA)

LIBSTOLINK    	:= -lm

#Compiler and archiver SECTION
TARGET 		:= Application
VERSION		:= Debugx64
CC 		:= gcc
ARCH		:= ar rcs
LIBSEARCHDIR	:= $(LIBDIRECTORY)/$(VERSION)/
LIBSRSEARCHPATH	:= $(LIBDIRECTORY)/$(VERSION)/
CFLAGS		:= -g -Wall
LDFLAGS		:= -L ../../$(LIBSEARCHDIR) $(LIBSTOLINK) \
	-Wl,-rpath,$(LIBSRSEARCHPATH)
MACROS		:= -D DEBUG\
		-D PI=3.1416\
                -D RESOURCES=\"/home/paul/Cprojects/Production/Encoder2/MechanicalWork/FreeCadFiles/Calculation_Program/Resources\"
#		-D RESOURCES=\"/home/pi/Encoder2/MechanicalWork/FreeCadFiles/Calculation_Program/Resources/\"\		

#RUNNING 

EXECINSTALLDIR	:= 
LIBINSTALLDIR	:= 
RESINSTALLDIR	:= 
