TOP_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

#CROSSCOMPILE SECTION
CROSSCOMPILE_HOSTNAME 	:= 
CROSSCOMPILE_SSH_HOST 	:= 
CROSSCOMPILE_DIR 	:= 

#PROJECT SECTION
TARGET 		:= Application
TESTTYPE	:= Debug
INSTRUCTIONS	:= x86
LIBRARIESTYPE	:= Static
VERSION		:= $(TESTTYPE)$(INSTRUCTIONS)$(LIBRARIESTYPE)

#The Directories and extensions SECTION
SRC_MODULES_DIR	   := Src_Modules
BUILDDIRECTORY 	   := Objects
TARGETDIRECTORY	   := Release
RESDIRECTORY  	   := Resources
LIBDIRECTORY	   := Libraries
HEADERSDIRECTORY   := Headers

DLEXT   := so
SLEXT	:= a
CCEXT	:= c
CPPEXT	:= cpp
OBJEXT	:= o
HEADEXT	:= h
SRCDIR	:= src

#Modules SECTION
MODULEA := Application

DEPMODULES	:= 
MAINMODULE	:= $(MODULEA)

#Compiler and archiver SECTION
PREFIX		:= 
CC		:= $(PREFIX)-gcc
CXX	  	:= $(PREFIX)-g++ 
LD		:= $(PREFIX)-gcc 
AR		:= $(PREFIX)-ar rcs
SIZE		:= $(PREFIX)-size
OPT		:= -Os -g
MACROS		:= -D DEBUG\
		-D PI=3.1416\

CFLAGS		+= $(OPT) -std=c99
CFLAGS		+= -Wextra -Wshadow -Wimplicit-function-declaration
CFLAGS		+= -Wredundant-decls -Wmissing-prototypes -Wstrict-prototypes
CFLAGS		+= -ffunction-sections -fdata-sections

CXXFLAGS	+= $(OPT) -std=c++11
CXXFLAGS	+= -Wextra -Wshadow -Wredundant-decls -Weffc++
CXXFLAGS	+= -fno-exceptions -fno-rtti
CXXFLAGS	+= -ffunction-sections -fdata-sections

CPPFLAGS	+= -MMD -MP
CPPFLAGS 	+= -Wall $(MACROS)

LIBSTOLINK    	:= -lm
LIBSEARCHDIR	:= $(LIBDIRECTORY)/$(VERSION)/
LIBSRSEARCHPATH	:= $(LIBDIRECTORY)/$(VERSION)/

LDFLAGS		+= -L ../../$(LIBSEARCHDIR) $(LIBSTOLINK) \
	-Wl,-rpath,$(LIBSRSEARCHPATH)

#RUNNING
EXECINSTALLDIR	:= 
LIBINSTALLDIR	:= 
RESINSTALLDIR	:= 
